### ISSUE TITLE
[c05f7883] error raised in plotPvalStats.R

### ISSUE THREAD

**Issue by croth1** [soedinglab/BaMM_webserver#91]
needs investigation.

**Comment by WanwanGe** [comment]
Fixed it! The main problem is the weird p-values. It causes NAs in qval calculation in fdrtool. After fixing the p-value calculation, this problem is gone. But we need to get rid of the dependency on fdrtool in the furture because it is not that robust. The current code on BaMMmotif2/master branch is up-to-date.

**Comment by WanwanGe** [comment]
The problem was raised when there were p-values equal to 0. The problem has been taken care of now.
